# Site settings
author: Alexander
title: My Flatiron School Blog
header-img: img/home-bg.png
email: alexander.clamor@gmail.com
copyright_name: Alexander
description: > # this means to ignore newlines until "baseurl:"
  Lessons learned
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alexander-mc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
